#include "Print.h"

void printInit(USART_TypeDef *UART)
{
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN; //GPIO A  ENABLE
	RCC->APB1ENR |= RCC_APB1ENR_USART2EN; //UART2 ENABLE
	
	GPIOA->MODER &= ~GPIO_MODER_MODER2_Msk;  //GPIO A PIN 2 ALTERNATE FUNCTION MODE
	GPIOA->MODER |= GPIO_MODER_MODER2_1;
	
	GPIOA->MODER &= ~GPIO_MODER_MODER3_Msk;  //GPIO A PIN 3 ALTERNATE FUNCTION MODE
	GPIOA->MODER |= GPIO_MODER_MODER3_1;
	
	GPIOA->AFR[0] |= (GPIO_AFRL_AFRL2_0 | GPIO_AFRL_AFRL2_1 | GPIO_AFRL_AFRL2_2); //GPIO ALTERNATE FUNCTION REGISTER PINS 2 AND 3 SET 7
	GPIOA->AFR[0] |= (GPIO_AFRL_AFRL3_0 | GPIO_AFRL_AFRL3_1  | GPIO_AFRL_AFRL3_2);

	UART->CR1 |= USART_CR1_TE; //USART2 TRANSMITTER ENABLE
	UART->CR1 |= USART_CR1_RE; //USART2 RECIEVER ENABLE
	
	//USART2->BRR = 0x0016C; //BAUD 115200
	UART->BRR = 0x13; //BAUD 2200000
	//USART2->BRR = (uint32_t)(42000000 / (16 * baudrate)) << 4;

	UART->CR1 |= USART_CR1_UE; //USART2 ENABLE
	
	P_UART = UART;
}

void print(char *msg, ...)
{
	char buff[80];
	
	va_list args;
	va_start(args, msg);
	vsprintf(buff, msg, args);
	
	for(uint8_t i = 0; i < strlen(buff); i++)
	{
		while(!(P_UART->SR & USART_SR_TXE));
		P_UART->DR = buff[i];
	}
	
}
